// This file can hold global constants for the games.

export const GAME_TIMER_SECONDS = 90;

export const POINTS = {
  GEM_CUT: 100,
  GEM_MISS: -50,
  REACH_EXIT: 500,
  STEP_TAKEN: 10,
  DESTROY_SMALL_ALIEN: 50,
  DESTROY_LARGE_ALIEN: 100,
  WAVE_SURVIVED: 200,
  EXTINGUISH_FIRE: 100,
  DEFEAT_FLAME_MONSTER: 200,
  NEW_FIRE_IGNITES: -50,
  CROSS_LANE: 50,
  REACH_FOREST: 500,
};

export const HEALTH = {
  EXPLOSIVE_DAMAGE: 25,
  FLAME_MONSTER_DAMAGE: 25,
};
